-- Merchant / partner-sponsored Benefit Program proposals.
-- Business partners may propose value; only Coveted System Admin can convert a
-- submitted proposal into a canonical Benefit Program draft.

CREATE TABLE IF NOT EXISTS benefit_sponsorship_proposals (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  public_id VARCHAR(64) NOT NULL UNIQUE,
  business_id BIGINT UNSIGNED NOT NULL,
  group_id BIGINT UNSIGNED NOT NULL,
  event_id BIGINT UNSIGNED NULL,
  location_id BIGINT UNSIGNED NOT NULL,
  created_by_user_id BIGINT UNSIGNED NOT NULL,
  program_title VARCHAR(190) NOT NULL,
  reward_title VARCHAR(190) NOT NULL,
  description TEXT NULL,
  reward_type ENUM('credit','free_item','discount','perk','access','service','audio','video','media_pack','experience','custom') NOT NULL DEFAULT 'perk',
  claim_mode ENUM('none','location_code') NOT NULL DEFAULT 'location_code',
  trigger_key ENUM('attendance','completion','return_visit','guest_return','manual') NOT NULL DEFAULT 'attendance',
  quantity_limit INT UNSIGNED NOT NULL,
  per_user_limit INT UNSIGNED NOT NULL DEFAULT 1,
  value_amount DECIMAL(12,2) NULL,
  value_text VARCHAR(255) NULL,
  starts_at DATETIME NULL,
  ends_at DATETIME NULL,
  status ENUM('submitted','declined','cancelled','converted') NOT NULL DEFAULT 'submitted',
  review_note VARCHAR(1000) NULL,
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  benefit_program_ref VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_benefit_sponsorship_program (benefit_program_ref),
  KEY idx_benefit_sponsorship_business_status (business_id,status,created_at),
  KEY idx_benefit_sponsorship_group_status (group_id,status,created_at),
  KEY idx_benefit_sponsorship_event_status (event_id,status,created_at),
  KEY idx_benefit_sponsorship_location_status (location_id,status,created_at),
  CONSTRAINT fk_benefit_sponsorship_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
  CONSTRAINT fk_benefit_sponsorship_group FOREIGN KEY (group_id) REFERENCES social_groups(id) ON DELETE RESTRICT,
  CONSTRAINT fk_benefit_sponsorship_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL,
  CONSTRAINT fk_benefit_sponsorship_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE RESTRICT,
  CONSTRAINT fk_benefit_sponsorship_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_benefit_sponsorship_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_benefit_sponsorship_quantity CHECK (quantity_limit >= 1),
  CONSTRAINT chk_benefit_sponsorship_per_user CHECK (per_user_limit >= 1),
  CONSTRAINT chk_benefit_sponsorship_window CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
